### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by bmfmancini**
Update Readme to move spine doc to data collection section 
update Discovered device section

### CODE REVIEW

**Comment by TheWitness** [comment]
Sean, can you please change the images to png?  Shouldn't take too long.  We need to move all of them to png IMHO.

**Comment by bmfmancini** [comment]
Sure no worries
I'll change it in a bit

**Comment by bmfmancini** [comment]
@TheWitness  I updated the images to png

**Comment by TheWitness** [comment]
Make the Discovered-devices.png lower case and remove that one JPG still there.

**Comment by TheWitness** [comment]
I'll be back at the HO in 35 minutes.

**Comment by bmfmancini** [comment]
@TheWitness  I removed it didnt actually need that file

**Comment by TheWitness** [comment]
Cool.  I'll be pounding out doco updates tonight for a few more hours anyway.

**Pull request merged**
