### PR TITLE
Create Installing-Under-Ubuntu-Debian.md

### PR DESCRIPTION
**Pull request by bmfmancini**
New document for Installing cacti 1.x on Ubuntu/Debian
Includes a youtube video as well

### CODE REVIEW

**Comment by netniV** [comment]
This has inline HTML tags, please try to stick to our [Documentation Standards](https://github.com/Cacti/documentation/blob/develop/Standards-Documentation.md)

**Comment by bmfmancini** [comment]
removed html tags

**Comment by cigamit** [comment]
@bmfmancini, is this one ready?  I see some conflicts

**Comment by bmfmancini** [comment]
Hey @cigamit  this was part of my other pull request
I will close this one

**Pull request closed without merging**
