### PR TITLE
Adding missing files dev-standards_sql_standards.txt and dev-standard…

### PR DESCRIPTION
**Pull request by jpobeda**
Special note: I'm assuming you don't want the subversion file from this link:
https://docs.cacti.net/dev_standards:subversion

https://docs.cacti.net/dev_standards:security#security
https://docs.cacti.net/dev_standards:sql_standards

### CODE REVIEW

**Comment by netniV** [comment]
Hi Javier,

You will notice I've been at work again.... your new files are not including in the index, so your commit is failing 👎 

###### Travis output:
```
The command "./check_markdown_style.sh" exited with 0.
0.12s$ ./check_missing_link.sh
Not Linked: Standards-SQL.md
Not Linked: Standards-Security.md
2 unlinked files
The command "./check_missing_link.sh" exited with 2.
```

**Comment by jpobeda** [comment]
@netniV you nasty ...I'll fix it in a 5 min

**Comment by jpobeda** [comment]
Shall we add this extra step to doc standards?

**Comment by netniV** [comment]
Yeah but I've just done something else, I updated README.md... I think you'll agree with the update, but let me know.

**Comment by netniV** [comment]
You'll need to do a `git rebase` after fetching the latest changes, then probably a `git push -f` from your repo

**Comment by netniV** [comment]
No, but we should probably have one for the git `pre-commit` script I use as it would be useful for others, especially given it would help prevent failures down the line if they are validated earlier.

**Comment by jpobeda** [comment]
Oh I see...I did wrong again then. Give me a min

**Comment by netniV** [comment]
No, it was me.  I went to fix the typo and thought, this is getting long and messy.  It needs SECTIONS! 🤒

**Pull request merged**
