### PR TITLE
New images based on Modern theme

### PR DESCRIPTION
**Pull request by jpobeda**
These images should be updated to reflect the new themes styles and interface changes. 
Are there any plans to update the documentation?

### CODE REVIEW

**Comment by netniV** [comment]
Travis is failing because we added markdown checking.  There are clearly a lot of things to correct.  However, I was also trying to check whether the documentation was complete against the original docs.cacti.net.  

However, none of that should affect the above images so I'll look over the images tonight and commit.

**Comment by netniV** [comment]
Out of curiosity, is this based against 1.1 or 1.2?

**Comment by ronytomen** [comment]
Merged, still working on the Markdown syntax checker.  Sorry for the confusion and inconvenience!

**Comment by jpobeda** [comment]
@netniV they are based on 1.1 but I didn't see substantial differences compared to 1.2, in terms of look & feel.
I think pictures and text from 'variables' section will need some tweaking to be honest. That part has changed a bit with 1.x version.

**Comment by netniV** [comment]
As we are updating the documentation, I think we need to get it up to the 1.2 level or we will end up duplicating work for everyone.  There have been a lot of changes, mostly subtle, to 1.2 but the screens in quite a few places will look a bit different (especially the installer as you mentioned).

**Comment by netniV** [comment]
Hopefully, a new update is coming ;-)

**Pull request closed without merging**
