### PR TITLE
Update How-To-Setup-Remote-Pollers.md

### PR DESCRIPTION
**Pull request by bmfmancini**
Add video tutorial on how to install remote data collectors

### CODE REVIEW

**Comment by netniV** [comment]
Thanks for the links.  I am going to review this more fully but at the moment, one point I noticed was in the first few minutes that I have watched, you mention remote pollers updating their local RRA files, this only happens on the main poller.  

The remote pollers store their data until the main poller can be seen again.  At that point, all old data is sync'd and the main poller then catches those RRA files up.

If you want to email me directly, I can offer some further suggestions plus I'm curious what tools you are using 👍

**Comment by bmfmancini** [comment]
Ok cool sounds good will do

**Comment by bmfmancini** [comment]
I sent you a PM on the forums I didn't have your email

**Comment by netniV** [comment]
just change developers to my name at cacti 👍

**Comment by bmfmancini** [comment]
cool just sent you  a email let me know if you got it 
I also sent one to developers yesterday with some ideas

**Pull request closed without merging**
