### PR TITLE
Added a known issues page

### PR DESCRIPTION
**Pull request by bmfmancini**
This page will help users Identiy known issues and fixed for the Latest version of Cacti 
this could also be used as a historical known issue/Bug page for the latest x amount of releases 
this should help with repeat reports of the same issue

### CODE REVIEW

**Comment by netniV** [comment]
We kind of have this via the GitHub bug trackers and Changelog. Known issues should be ongoing things that aren’t being fixed

**Comment by netniV** [comment]
So for example, just before release  had we known about the cookie domain and didn’t fix it, that is when it should be in a known issue section.

**Comment by bmfmancini** [comment]
My thinking was right now if you go to the releases section of github and download 1.2.11 there is no where that says this is a known issue which is why for that particular issue there were multiple reports which would mean that that issue although known and fixed is not fixed in the zip or the tar

The release just shows the changes and the updates 
Unless we leverage that page and add another heading for known issues which is updated

**Comment by netniV** [comment]
Like I said that’s no long a known issue if it’s been resolved. The changelog does provide info but unfortunately when people come to GitHub to report their issue they can’t seem to search first and find a similar issue. 

GitHub has started to beta the searching of old issues based on what you’ve written so that can help.

**Comment by netniV** [comment]
In theory if there is an open bug that has not been resolved, those could potentially be known issues if we have confirmed them as reproducible

**Comment by bmfmancini** [comment]
Ok got it 

I will close the PR

Thanks !

**Comment by netniV** [comment]
Maybe there should be a known issues file in core. Or at least a wiki page.

**Comment by netniV** [comment]
Come to think of it. Importing packages can reset graphs back to defaults if people custom the default templates. That is a known issue that should be listed.

**Pull request closed without merging**
