### PR TITLE
Update Installing-Under-Ubuntu-Debian.md

### PR DESCRIPTION
**Pull request by bmfmancini**
add video tutorial

### CODE REVIEW

**Comment by TheWitness** [comment]
Sean, turn up the volume on that video.  I can barely hear you.

**Comment by TheWitness** [comment]
I had to goto 100% on everything to hear it well.

**Comment by bmfmancini** [comment]
Ok thanks for letting me know
I'll boost up the volume must be a ffmpeg problem

**Comment by TheWitness** [comment]
Yea, look at the comments on a few of the other videos, you theres some noise at around the 9 minute mark on one of them.  Either way, audio needs to be boosted big time.

**Comment by netniV** [comment]
Is this patch still valid? I thought a new version had been done.

**Comment by bmfmancini** [comment]
Yea I had to do a re-upload of the video just the URL needs to be changed I will update the PR now

**Comment by bmfmancini** [comment]
just updated the URL to the fixed video the other one had audio issues

**Comment by bmfmancini** [comment]
I see your point

I'd be glad to provide you the video files to upload on the groups own
YouTube page

**Pull request closed without merging**
